/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package infoAidTechTempConvertor;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Mr Sagar Kumar
 */
public class HomeConvertor extends javax.swing.JFrame {

    /**
     * Creates new form HomeConvertor
     */
    public HomeConvertor() {
        initComponents();
        ToTextField.setEditable(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        HeaderLabel = new javax.swing.JLabel();
        Four = new javax.swing.JButton();
        One = new javax.swing.JButton();
        Two = new javax.swing.JButton();
        Three = new javax.swing.JButton();
        Five = new javax.swing.JButton();
        Six = new javax.swing.JButton();
        Seven = new javax.swing.JButton();
        Eight = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Nine = new javax.swing.JButton();
        Zero = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        PicLabel = new javax.swing.JLabel();
        ToList = new javax.swing.JComboBox<>();
        ToTextField = new javax.swing.JTextField();
        FromTextField = new javax.swing.JTextField();
        FromList = new javax.swing.JComboBox<>();
        ConvertButton = new javax.swing.JButton();
        Celsius = new javax.swing.JLabel();
        Fahrenheit = new javax.swing.JLabel();
        MainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(51, 51, 51));
        MainPanel.setLayout(null);

        HeaderLabel.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        HeaderLabel.setForeground(new java.awt.Color(255, 255, 255));
        HeaderLabel.setText("Temperatur Convertor");
        MainPanel.add(HeaderLabel);
        HeaderLabel.setBounds(130, 20, 270, 40);

        Four.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Four.setText("4");
        Four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourActionPerformed(evt);
            }
        });
        MainPanel.add(Four);
        Four.setBounds(320, 290, 60, 40);

        One.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        One.setText("1");
        One.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneActionPerformed(evt);
            }
        });
        MainPanel.add(One);
        One.setBounds(140, 290, 60, 40);

        Two.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Two.setText("2");
        Two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoActionPerformed(evt);
            }
        });
        MainPanel.add(Two);
        Two.setBounds(200, 290, 60, 40);

        Three.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Three.setText("3");
        Three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeActionPerformed(evt);
            }
        });
        MainPanel.add(Three);
        Three.setBounds(260, 290, 60, 40);

        Five.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Five.setText("5");
        Five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveActionPerformed(evt);
            }
        });
        MainPanel.add(Five);
        Five.setBounds(140, 340, 60, 40);

        Six.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Six.setText("6");
        Six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixActionPerformed(evt);
            }
        });
        MainPanel.add(Six);
        Six.setBounds(200, 340, 60, 40);

        Seven.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Seven.setText("7");
        Seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenActionPerformed(evt);
            }
        });
        MainPanel.add(Seven);
        Seven.setBounds(260, 340, 60, 40);

        Eight.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Eight.setText("8");
        Eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightActionPerformed(evt);
            }
        });
        MainPanel.add(Eight);
        Eight.setBounds(320, 340, 60, 40);

        Clear.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Clear.setText("CE");
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        MainPanel.add(Clear);
        Clear.setBounds(140, 390, 60, 40);

        Nine.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Nine.setText("9");
        Nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NineActionPerformed(evt);
            }
        });
        MainPanel.add(Nine);
        Nine.setBounds(200, 390, 60, 40);

        Zero.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Zero.setText("0");
        Zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZeroActionPerformed(evt);
            }
        });
        MainPanel.add(Zero);
        Zero.setBounds(260, 390, 60, 40);

        Delete.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        Delete.setText("Del");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        MainPanel.add(Delete);
        Delete.setBounds(320, 390, 60, 40);

        PicLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PicLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infoAidTechTempConvertor/PICS/water-temperature.png"))); // NOI18N
        MainPanel.add(PicLabel);
        PicLabel.setBounds(-10, 0, 170, 120);

        ToList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit" }));
        MainPanel.add(ToList);
        ToList.setBounds(10, 280, 110, 40);
        MainPanel.add(ToTextField);
        ToTextField.setBounds(10, 230, 110, 40);
        MainPanel.add(FromTextField);
        FromTextField.setBounds(10, 130, 110, 40);

        FromList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit" }));
        MainPanel.add(FromList);
        FromList.setBounds(10, 180, 110, 40);

        ConvertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infoAidTechTempConvertor/PICS/thermostat.png"))); // NOI18N
        ConvertButton.setText("Convert");
        ConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertButtonActionPerformed(evt);
            }
        });
        MainPanel.add(ConvertButton);
        ConvertButton.setBounds(10, 350, 111, 40);

        Celsius.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Celsius.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infoAidTechTempConvertor/PICS/Celsuis.png"))); // NOI18N
        MainPanel.add(Celsius);
        Celsius.setBounds(270, 170, 30, 60);

        Fahrenheit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fahrenheit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infoAidTechTempConvertor/PICS/fahrenheit.png"))); // NOI18N
        MainPanel.add(Fahrenheit);
        Fahrenheit.setBounds(310, 170, 40, 60);

        MainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/infoAidTechTempConvertor/PICS/temperature.png"))); // NOI18N
        MainPanel.add(MainLabel);
        MainLabel.setBounds(170, 60, 550, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertButtonActionPerformed
    String from = (String) FromList.getSelectedItem();
    String to = (String) ToList.getSelectedItem();
    
    if (from.isEmpty() || to.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Select both the Convertible and Converted Temperatures.");
        return; // Stop further execution if one or both options are not selected
    }

    try {
        double temperature = Double.parseDouble(FromTextField.getText().trim());

        // Temperature conversion logic
        if (from.equals("Celsius") && to.equals("Fahrenheit")) {
            ToTextField.setText(String.format("%.3f",celsiusToFahrenheit(temperature)));
        } else if (from.equals("Fahrenheit") && to.equals("Celsius")) {
            ToTextField.setText(String.format("%.3f",fahrenheitToCelsius(temperature)));
        }
        else if (from.equals("Fahrenheit") && to.equals("Fahrenheit")) {
            ToTextField.setText(String.format("%.3f",temperature));
        }
         else if (from.equals("Celsius") && to.equals("Celsius")) {
            ToTextField.setText(String.format("%.3f",temperature));
        }
        else {
            JOptionPane.showMessageDialog(null, "Unsupported conversion: " + from + " to " + to);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid temperature input. Enter a valid number.");
    }    
    }//GEN-LAST:event_ConvertButtonActionPerformed
    
    private double celsiusToFahrenheit(double celsius) {
        return (celsius * 9 / 5) + 32;
    }

    private double fahrenheitToCelsius(double fahrenheit) {
        return (fahrenheit - 32) * 5 / 9;
    }
    
    private void OneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneActionPerformed
        
        FromTextField.setText(FromTextField.getText().trim()+"1");
    }//GEN-LAST:event_OneActionPerformed

    private void TwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoActionPerformed
         FromTextField.setText(FromTextField.getText().trim()+"2");
    }//GEN-LAST:event_TwoActionPerformed

    private void ThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeActionPerformed
        FromTextField.setText(FromTextField.getText().trim()+"3");
    }//GEN-LAST:event_ThreeActionPerformed

    private void FourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourActionPerformed
     FromTextField.setText(FromTextField.getText().trim()+"4");
    }//GEN-LAST:event_FourActionPerformed

    private void FiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveActionPerformed
         FromTextField.setText(FromTextField.getText().trim()+"5");
    }//GEN-LAST:event_FiveActionPerformed

    private void SixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixActionPerformed
         FromTextField.setText(FromTextField.getText().trim()+"6");
    }//GEN-LAST:event_SixActionPerformed

    private void SevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenActionPerformed
         FromTextField.setText(FromTextField.getText().trim()+"7");
    }//GEN-LAST:event_SevenActionPerformed

    private void EightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightActionPerformed
         FromTextField.setText(FromTextField.getText().trim()+"8");
    }//GEN-LAST:event_EightActionPerformed

    private void NineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NineActionPerformed
         FromTextField.setText(FromTextField.getText().trim()+"9");
    }//GEN-LAST:event_NineActionPerformed

    private void ZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZeroActionPerformed
         FromTextField.setText(FromTextField.getText().trim()+"0");
    }//GEN-LAST:event_ZeroActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
         FromTextField.setText("");
         ToTextField.setText("");
    }//GEN-LAST:event_ClearActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        if(FromTextField.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Enter the Temperature!");
        else
        FromTextField.setText(FromTextField.getText().substring(0, FromTextField.getText().length()-1));
        
    }//GEN-LAST:event_DeleteActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeConvertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeConvertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeConvertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeConvertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeConvertor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Celsius;
    private javax.swing.JButton Clear;
    private javax.swing.JButton ConvertButton;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Eight;
    private javax.swing.JLabel Fahrenheit;
    private javax.swing.JButton Five;
    private javax.swing.JButton Four;
    private javax.swing.JComboBox<String> FromList;
    private javax.swing.JTextField FromTextField;
    private javax.swing.JLabel HeaderLabel;
    private javax.swing.JLabel MainLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton Nine;
    private javax.swing.JButton One;
    private javax.swing.JLabel PicLabel;
    private javax.swing.JButton Seven;
    private javax.swing.JButton Six;
    private javax.swing.JButton Three;
    private javax.swing.JComboBox<String> ToList;
    private javax.swing.JTextField ToTextField;
    private javax.swing.JButton Two;
    private javax.swing.JButton Zero;
    // End of variables declaration//GEN-END:variables
}
